# This reads in DESeq2 differential OTU abundance results (must be run first) for two sets of results:
# 1) For all samples, testing diffrences between remnant and disturbed sites (Fig 3A)
# 2) For only remnant samples, testing differences between eastern and western sites (Fig 3B)
# and tabulates the counts of OTUs in each of the 9 possible outcomes for the two sets of results 
# (e.g. skewed towards remnants, skewed towards disturbed sites, or no skew) and plots the results
# as a contingency table (Figure 4).

# Working correctly 111917

library(RColorBrewer)

# Remnant DESEQ2 results
DESeq2ResultsRemn <- load("~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientCoordinated_DESEQ2_results_remnantSites.r")

# Subset into the sign p val OTUs
Remn_DESeq2_pValSorted <- as.data.frame(DESeq_remnant_WE_Compare_pValueSorted@listData)
row.names(Remn_DESeq2_pValSorted) <- DESeq_remnant_WE_Compare_pValueSorted@rownames

Remn_DESeq2_pValSorted_signSubset <- Remn_DESeq2_pValSorted[which(Remn_DESeq2_pValSorted$padj < 0.05),]

Remn_DESeq2_pValSorted_NONsignSubset <- Remn_DESeq2_pValSorted[which((Remn_DESeq2_pValSorted$padj >= 0.05) | is.na(Remn_DESeq2_pValSorted$padj)),]

# Subset into the west/east for remnant OTUs with significant skew
remnWesternOTUs <- Remn_DESeq2_pValSorted_signSubset[Remn_DESeq2_pValSorted_signSubset$log2FoldChange > 0,]
remnEasternOTUs <- Remn_DESeq2_pValSorted_signSubset[Remn_DESeq2_pValSorted_signSubset$log2FoldChange < 0,]

# Now have the remnant OTUs split, need to split the all sites OTUs by remn/dist skew.
# Load the data.
DESeq2ResultsAllSites <- load("~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientCoordinated_DESEQ2_results_allSamples.r")

# Subset into the sign p val OTUs
allSitesDESeq2_pValSorted <- as.data.frame(DESeq_distHistCompare_pValueSorted@listData)
row.names(allSitesDESeq2_pValSorted) <- DESeq_distHistCompare_pValueSorted@rownames

allSitesDESeq2_pValSorted_signSubset <- allSitesDESeq2_pValSorted[which(allSitesDESeq2_pValSorted$padj < 0.05),]

# Subset into the remn/dist for remnant OTUs with significant skew
allSitesRemnOTUs <- allSitesDESeq2_pValSorted_signSubset[allSitesDESeq2_pValSorted_signSubset$log2FoldChange > 0,]
allSitesDistOTUs <- allSitesDESeq2_pValSorted_signSubset[allSitesDESeq2_pValSorted_signSubset$log2FoldChange < 0,]

allSitesDESeq2_pValSorted_NONsignSubset <- allSitesDESeq2_pValSorted[which((allSitesDESeq2_pValSorted$padj >= 0.05) | is.na(allSitesDESeq2_pValSorted$padj)),]

# The contingency table will be set up like so:
#  Cell1 - R/E.   Cell2 - R/No.    Cell3 - R/W.
#  Cell4 - No/E.  Cell5 - No/No.   Cell6 - No/W.
#  Cell7 - D/E.   Cell8 - D/No.    Cell9 - D/W.

cell1OTUFlag <- row.names(allSitesRemnOTUs) %in% row.names(remnEasternOTUs)
cell2OTUFlag <- row.names(allSitesRemnOTUs) %in% row.names(Remn_DESeq2_pValSorted_NONsignSubset)
cell3OTUFlag <- row.names(allSitesRemnOTUs) %in% row.names(remnWesternOTUs)

cell4OTUFlag <- row.names(allSitesDESeq2_pValSorted_NONsignSubset) %in% row.names(remnEasternOTUs)
cell5OTUFlag <- row.names(allSitesDESeq2_pValSorted_NONsignSubset) %in% row.names(Remn_DESeq2_pValSorted_NONsignSubset)
cell6OTUFlag <- row.names(allSitesDESeq2_pValSorted_NONsignSubset) %in% row.names(remnWesternOTUs)

cell7OTUFlag <- row.names(allSitesDistOTUs) %in% row.names(remnEasternOTUs)
cell8OTUFlag <- row.names(allSitesDistOTUs) %in% row.names(Remn_DESeq2_pValSorted_NONsignSubset)
cell9OTUFlag <- row.names(allSitesDistOTUs) %in% row.names(remnWesternOTUs)


cell1OTUs <- row.names(allSitesRemnOTUs)[cell1OTUFlag]
cell2OTUs <- row.names(allSitesRemnOTUs)[cell2OTUFlag]
cell3OTUs <- row.names(allSitesRemnOTUs)[cell3OTUFlag]

cell4OTUs <- row.names(allSitesDESeq2_pValSorted_NONsignSubset)[cell4OTUFlag]
cell5OTUs <- row.names(allSitesDESeq2_pValSorted_NONsignSubset)[cell5OTUFlag]
cell6OTUs <- row.names(allSitesDESeq2_pValSorted_NONsignSubset)[cell6OTUFlag]

cell7OTUs <- row.names(allSitesDistOTUs)[cell7OTUFlag]
cell8OTUs <- row.names(allSitesDistOTUs)[cell8OTUFlag]
cell9OTUs <- row.names(allSitesDistOTUs)[cell9OTUFlag]

print(paste("numEntries in Cell1 (R/E) is:", length(cell1OTUs)))
print(paste("numEntries in Cell2 (R/No) is:", length(cell2OTUs)))
print(paste("numEntries in Cell3 (R/W) is:", length(cell3OTUs)))

print(paste("numEntries in Cell4 (No/E) is:", length(cell4OTUs)))
print(paste("numEntries in Cell5 (No/No) is:", length(cell5OTUs)))
print(paste("numEntries in Cell6 (No/W) is:", length(cell6OTUs)))

print(paste("numEntries in Cell7 (D/E) is:", length(cell7OTUs)))
print(paste("numEntries in Cell8 (D/No) is:", length(cell8OTUs)))
print(paste("numEntries in Cell9 (D/W) is:", length(cell9OTUs)))

obsTable <- matrix(c(length(cell1OTUs), length(cell2OTUs), length(cell3OTUs),
                         length(cell4OTUs), length(cell5OTUs), length(cell6OTUs),
                         length(cell7OTUs), length(cell8OTUs), length(cell9OTUs)), nrow = 3, byrow = TRUE)


print(chisq.test(obsTable))

# Add marginal totals to the observed counts table.
obsTable_margTot <- matrix(c(obsTable[1,], sum(obsTable[1,]),
                                                obsTable[2,], sum(obsTable[2,]),
                                                obsTable[3,], sum(obsTable[3,]),
                                                sum(obsTable[,1]),sum(obsTable[,2]),sum(obsTable[,3]),sum(obsTable)),
                           nrow = 4, byrow = TRUE)

totalCount <- obsTable_margTot[4,4]

expectedCountsTable <- matrix(c((obsTable_margTot[4,1] * obsTable_margTot[1,4])/totalCount, (obsTable_margTot[4,2] * obsTable_margTot[1,4])/totalCount,
                                (obsTable_margTot[4,3] * obsTable_margTot[1,4])/totalCount, (obsTable_margTot[4,1] * obsTable_margTot[2,4])/totalCount,
                                (obsTable_margTot[4,2] * obsTable_margTot[2,4])/totalCount, (obsTable_margTot[4,3] * obsTable_margTot[2,4])/totalCount,
                                (obsTable_margTot[4,1] * obsTable_margTot[3,4])/totalCount, (obsTable_margTot[4,2] * obsTable_margTot[3,4])/totalCount,
                                (obsTable_margTot[4,3] * obsTable_margTot[3,4])/totalCount), nrow = 3, byrow = TRUE)

obsDivByExp <- obsTable / expectedCountsTable


par(mar=c(4.1,7.1,7.1,4.5))

colorBreaksVect <- c(-1.75, -1.25, -0.75, -0.25, 0.25, 0.75, 1.25, 1.75, 2.25, 2.75, 3.25)


colorIntervalVect <- findInterval(as.vector(obsDivByExp), colorBreaksVect, all.inside = TRUE)

colors <- c("#8E0152","#C51B7D","#DE77AE","#F1B6DA","#FDE0EF", "#F7F7F7", "#B8E186", "#7FBC41", "#4D9221", "#276419")


# Create a color vector using the grouping vector as an index
colorsVect <- colors[colorIntervalVect]


image(t(obsDivByExp), ylim = c(1.25, -0.25), xlim = c(1.25, -0.25), col = colors, xaxp = c(-0.25,1.25,3),
      yaxp = c(-0.25,1.25,3),breaks = c(-1.75, -1.25, -0.75, -0.25, 0.25, 0.75, 1.25, 1.75, 2.25, 2.75, 3.25),
      xaxt = "n", yaxt = "n")

# ---------
# y axis labels
mtext(text = c("Remn. skew", "No skew", "Dist. skew"), side = 2,
       at = c(0.0, 0.5, 1), las = 3, line = 0.3, cex = 2)

mtext(text = c("All sites"), side = 2,
      at = 0.5, las = 3, line = 4, cex = 3)

# ----------

# ----------
# x axis labels - axis flipped, so label order flipped when plots

mtext(text = c("East skew", "No skew", "West skew"), side = 3,
      at = c(0.0, 0.5, 1), las = 1, line = 0.3, cex = 2)

mtext(text = c("Remnant sites only"), side = 3,
      at = 0.5, las = 1, line = 4, cex = 3)


# ----------

# to get number of decimals right...
specify_decimal <- function(x, k) format(round(x, k), nsmall=k)

# This is the observed counts
text(c(0,0.5,1,0,0.5,1,0,0.5,1),
     c(0.125,0.125,0.125,0.625,0.625,0.625,1.125,1.125,1.125),
     labels = c(paste0("(", specify_decimal(expectedCountsTable[1,1],1),")"),
                paste0("(", specify_decimal(expectedCountsTable[1,2],1),")"),
                paste0("(", specify_decimal(expectedCountsTable[1,3],1),")"),
                paste0("(", specify_decimal(expectedCountsTable[2,1],1),")"),
                paste0("(", specify_decimal(expectedCountsTable[2,2],1),")"),
                paste0("(", specify_decimal(expectedCountsTable[2,3],1),")"),
                paste0("(", specify_decimal(expectedCountsTable[3,1],1),")"),
                paste0("(", specify_decimal(expectedCountsTable[3,2],1),")"),
                paste0("(", specify_decimal(expectedCountsTable[3,3],1),")")),
     col = c("white","black","black","black","black","black","black","black","black"),
     cex = 4)
# This is the ratio of the observed counts to the predicted counts
# truncated to 2 decimals.



text(c(0,0.5,1,0,0.5,1,0,0.5,1),
     c(-0.125,-0.125,-0.1250,0.375,0.375,0.375,0.875,0.875,0.875),
     labels = c(obsTable[1,1],
                obsTable[1,2],
                obsTable[1,3],
                obsTable[2,1],
                obsTable[2,2],
                obsTable[2,3],
                obsTable[3,1],
                obsTable[3,2],
                obsTable[3,3]),
     col = c("white","black","black","black","black","black","black","black","black"),
     cex = 4)

abline(v = c(0.25, 0.75))
abline(h = c(0.25, 0.75), lwd = c(1,1))

# Marginal sums

allSampRemnSkewSum <- length(cell1OTUs) + length(cell2OTUs) + length(cell3OTUs)
allSampNoSkewSum <- length(cell4OTUs) + length(cell5OTUs) + length(cell6OTUs)
allSampDistSkewSum <- length(cell7OTUs) + length(cell8OTUs) + length(cell9OTUs)

remnSampleWestSkewSum <- length(cell1OTUs) + length(cell4OTUs) + length(cell7OTUs)
remnSampleNoSkewSum <- length(cell2OTUs) + length(cell5OTUs) + length(cell8OTUs)
remnSampleEastSkewSum <- length(cell3OTUs) + length(cell6OTUs) + length(cell9OTUs)

mtext(text = c(allSampRemnSkewSum, allSampNoSkewSum, allSampDistSkewSum), side = 4,
      at = c(0.0, 0.5, 1), las = 1, line = 0.5, cex = 3)

mtext(text = c(remnSampleWestSkewSum, remnSampleNoSkewSum, remnSampleEastSkewSum), side = 1,
      at = c(0.0, 0.5, 1), las = 1, line = 1.5, cex = 3)