# This generates and saves the rLog transformations of the OTU table as input for linear discriminant analysis

# Working correctly for all samples 111917. 

library('phyloseq')
library('DESeq2')

# Import the OTU table
OTUTableGradient <- read.table("~/Prairie-AMF-Gradient-Analysis-master/GradientAMF_OTUTable_forR.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# Import the AM fungal OTU numbers (identified from the phylogeny with reference sequences, Appendix 1, Figure S1).
AMFOTUNumbers <- scan("~/Prairie-AMF-Gradient-Analysis-master/GradientAMF_AMF_OTUNumbers_forR.txt")

# Remove the labels and other information columns to keep only the OTU table counts
OTUframeGradient <- data.frame(OTUTableGradient[,5:length(OTUTableGradient[1,])])

# This works correctly to subset only the AMF OTU columns by moving them by name (eg X1,X12) 
gradientSamplesOnlyGradientFrame <- OTUframeGradient[,paste("X",AMFOTUNumbers,sep="")]

# Add the sample names back to the otu table data frame as rownames
gradientSamplesOnlyGradientFrame_names <- OTUTableGradient[,4]
rownames(gradientSamplesOnlyGradientFrame) <- gradientSamplesOnlyGradientFrame_names

# Import environmental and soil chemical values for each seq barcode
gradientEnvAndSoilChemValues <- read.table("~/Prairie-AMF-Gradient-Analysis-master/GradientAMF_environ_soilNutrient_values_forR.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

gradientEnvAndSoilChemValues <- gradientEnvAndSoilChemValues[,-1:-3]
rownames(gradientEnvAndSoilChemValues) <- gradientSamplesOnlyGradientFrame_names

# East/West geographic groups.
# West: Klemme, Stillwater, Hays, Ft. Riley (2013), Konza (2015)
# East: Lawrence (Rockefeller and Welda), SW MO, Morris, IL (2013), IL (2015)
geogrGroupWE <- c(rep("W", 7), rep("E", 2), rep("W", 4), rep("E", 8), rep("W", 17), rep("E", 13),
                  rep("W", 4), rep("E", 17), rep("W", 20), rep("E", 3), rep("W", 6), rep("E", 7))

# Control for geographic location (need to lump remn/dist site at each geogr loc to 
# get a matrix model that is full rank)
siteGroup <- c(rep("Klemme", 3), rep("Hays", 4), rep("Lawrence", 2), rep("Konza", 2),
               rep("Klemme",1), rep("Konza", 1), rep("SW_MO", 4), rep("Morris",2),
               rep("Lawrence", 2), rep("Klemme", 8), rep("Hays", 5), rep("Konza", 4),
               rep("Lawrence", 7), rep("IL_2015", 6), rep("Konza", 4), rep("Lawrence", 1),
               rep("SW_MO", 8), rep("Morris",2), rep("IL_2015", 6), rep("Stillwater", 7),
               rep("FtRiley", 13), rep("IL_2013", 3), rep("FtRiley", 6), rep("IL_2013", 7))

siteGroupFactor <- as.factor(siteGroup)
gradientEnvAndSoilChemValues$siteGroup <- siteGroupFactor

gradientEnvAndSoilChemValues$geogrGroupWE <- as.factor(geogrGroupWE)

gradientEnvAndSoilChemValues$distGroup <- as.factor(gradientEnvAndSoilChemValues$Disturbed_Remnant)

# Add pseudo count - this is REQUIRED  to be able to run the rlog transformation below and the DESeq analysis.
gradientSamplesOnlyGradientFrame <- gradientSamplesOnlyGradientFrame + 1

#======================
#======================
# These are the analyses as of 120416

#-----------------
# This is the transformation for testing for disturbed/remn differences across both W and E sites; The rlog
# transform controls for
# geographic location the best I can with DESeq2 (same as the DESEQ2 analysis I'm using.)

outputFile <- "~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientAMF_rLogTransformOTUTable_controlGeogrLoc_allSites.r"

# Convert OTU table to phyloseq OTU table
phyloseq_OTUTable <- otu_table(gradientSamplesOnlyGradientFrame, taxa_are_rows = FALSE)

# This seems to work, but View() fails on it....
phyloseq_sampleData <- sample_data(gradientEnvAndSoilChemValues)

phyloseq_combined <- phyloseq(phyloseq_OTUTable, phyloseq_sampleData)

# Design '~ 1' is valid for not specifying a design in phyloseq_to_deseq2

OTU_sampleDataForRLog <- phyloseq_to_deseq2(phyloseq_combined, ~ siteGroup)

# Do the (non-blind) rlog transformation
rlogTransformation_allSites_siteGroupControlled <- rlog(OTU_sampleDataForRLog, fitType = 'local', blind = FALSE)

save(rlogTransformation_allSites_siteGroupControlled, file = outputFile)

#-----------------

#-----------------
# This is the transformation for testing for location (West/East) differences for only REMNANT sites; The rlog
# DOES NOT controls for
# geographic location because of how the sampling was performed along a gradient.

gradientSamplesOnlyGradientFrame_noMissing_Remnant <- gradientSamplesOnlyGradientFrame[gradientEnvAndSoilChemValues$distGroup == 'Remnant',]
subsetGradientEnvAndSoilChemValues_abbrv_Remnant <- gradientEnvAndSoilChemValues[gradientEnvAndSoilChemValues$distGroup == 'Remnant',]

outputFile <- "~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientAMF_rLogTransformOTUTable_onlyRemnantSites.r"

# Convert OTU table to phyloseq OTU table
phyloseq_OTUTable <- otu_table(gradientSamplesOnlyGradientFrame_noMissing_Remnant, taxa_are_rows = FALSE)

# This seems to work, but View() fails on it....
phyloseq_sampleData <- sample_data(subsetGradientEnvAndSoilChemValues_abbrv_Remnant)

phyloseq_combined <- phyloseq(phyloseq_OTUTable, phyloseq_sampleData)

# Design '~ 1' is valid for not specifying a design in phyloseq_to_deseq2

OTU_sampleDataForRLog <- phyloseq_to_deseq2(phyloseq_combined, ~ 1)

# Do the (non-blind) rlog transformation
rlogTransformation_RemnantSites <- rlog(OTU_sampleDataForRLog, fitType = 'local', blind = FALSE)

save(rlogTransformation_RemnantSites, file = outputFile)

# #-----------------

# #-----------------
# This is the transformation for testing for location (West/East) differences for only DISTURBED sites; The rlog
# DOES NOT controls for
# geographic location because of how the sampling was performed along a gradient.

gradientSamplesOnlyGradientFrame_noMissing_Disturbed <- gradientSamplesOnlyGradientFrame[gradientEnvAndSoilChemValues$distGroup == 'Disturbed',]
subsetGradientEnvAndSoilChemValues_abbrv_Disturbed <- gradientEnvAndSoilChemValues[gradientEnvAndSoilChemValues$distGroup == 'Disturbed',]

outputFile <- "~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientAMF_rLogTransformOTUTable_onlyDisturbedSites.r"

# Convert OTU table to phyloseq OTU table
phyloseq_OTUTable <- otu_table(gradientSamplesOnlyGradientFrame_noMissing_Disturbed, taxa_are_rows = FALSE)

# This seems to work, but View() fails on it....
phyloseq_sampleData <- sample_data(subsetGradientEnvAndSoilChemValues_abbrv_Disturbed)

phyloseq_combined <- phyloseq(phyloseq_OTUTable, phyloseq_sampleData)

# Design '~ 1' is valid for not specifying a design in phyloseq_to_deseq2

OTU_sampleDataForRLog <- phyloseq_to_deseq2(phyloseq_combined, ~ 1)

# Do the (non-blind) rlog transformation
rlogTransformation_DisturbedSites <- rlog(OTU_sampleDataForRLog, fitType = 'local', blind = FALSE)

save(rlogTransformation_DisturbedSites, file = outputFile)

# #-----------------