# This calculates the pairwise correlations between all environmental variables for Table S2.

# This is working correctly 112117.

library(picante)

# Import environmental and soil chemical values for each seq barcode
gradientEnvAndSoilChemValues <- read.table("~/Prairie-AMF-Gradient-Analysis-master/GradientAMF_environ_soilNutrient_values_forR.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# Subset the environmental values to only the samples that contain C/N measures, and exclude those from
# Klemme (so no samples from Oklahoma are considered)
soilNutrValuesForCapscale <- gradientEnvAndSoilChemValues[which(!is.na(gradientEnvAndSoilChemValues$C_N)),]

soilNutrValuesForCapscale <- soilNutrValuesForCapscale[which(soilNutrValuesForCapscale$Site != "Klemme"),]

distGroup <- c(rep("Disturbed",11),rep("Remnant",31),rep("Disturbed",3),rep("Remnant",1),rep("Disturbed",1),rep("Remnant",1),rep("Disturbed",3),
               rep("Remnant",1),rep("Disturbed",2),rep("Remnant",1),
               rep("Disturbed",4),rep("Remnant",1),rep("Disturbed",1),rep("Remnant",1),rep("Disturbed",1),
               rep("Remnant",1),rep("Disturbed",2),rep("Remnant",6))

# @@@@@@@@@@@@@@@@@@@@@
#

# Make pairwise correlation scatter plots for the different soil vars
pairs(~ log(NOAA_AnnualPrecip_mm) + NOAA_aridityIndex_P.PET + NOAA_meanAnnualTemp_degC +
        perc_OM + log(Bray1P_ppm) + log(Bray2P_ppm) + log(bicarbP_ppm) + soil_pH + log(CEC_meqPer100g) + C_N +
        log(K_ppm) + log(Ca_ppm) + log(Mg_ppm) + log(bicarbP_ppm), bg = c("purple","orange")[soilNutrValuesForCapscale$Disturbed_Remnant],
      pch = 21, cex = 1, data = soilNutrValuesForCapscale)

# Don't need to log-transform any vars since this is a rank order correlation, and the correlation is identical
# regardless of whether the data are transformed or not. The distHist can take any numeric values and give the same
# results, again because it's the rank order correlation.
dataForCorr <- data.frame(distHist = ifelse(distGroup == "Remnant", 1,0),
                          precip = soilNutrValuesForCapscale$NOAA_AnnualPrecip_mm, 
                          aridity = soilNutrValuesForCapscale$NOAA_aridityIndex_P.PET,
                          temp = soilNutrValuesForCapscale$NOAA_meanAnnualTemp_degC, 
                          OM = soilNutrValuesForCapscale$perc_OM, 
                          bray1P = soilNutrValuesForCapscale$Bray1P_ppm, 
                          bray2P = soilNutrValuesForCapscale$Bray2P_ppm, 
                          bicarbP = soilNutrValuesForCapscale$bicarbP_ppm, 
                          pH = soilNutrValuesForCapscale$soil_pH, 
                          CEC = soilNutrValuesForCapscale$CEC_meqPer100g, 
                          CN = soilNutrValuesForCapscale$C_N,
                          K = soilNutrValuesForCapscale$K_ppm, 
                          Ca = soilNutrValuesForCapscale$Ca_ppm, 
                          Mg = soilNutrValuesForCapscale$Mg_ppm)



# This runs all possible pairs of correlations and outputs the results in matrix form (matrix of p values, matrix
# of correlation r values, and df in a dataframe)
pairCorrelations <- cor.table(dataForCorr, cor.method = "spearman")

# Write the raw correlations
write.csv(pairCorrelations$r, file = "~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientAMF_soilNutrientsCorrelations_corrValues.csv")

# Write the p values for the correlations
write.csv(pairCorrelations$P, file = "~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientAMF_soilNutrientsCorrelations_PValues.csv")
