# NRI based on DESEQ2 corrected relative abundance values (which are already set up as a pairwise
# comparison)

# This is working correctly 111917

library(ape)
library(PhyloMeasures)
library(picante)

# This is revised with Mor elo outgroup 072117
OTUNames_fromPhylo <- read.table("~/Prairie-AMF-Gradient-Analysis-master/GradientAMF_OTU_GenusAttributions_forR.csv", sep = ",", header = TRUE, stringsAsFactors = FALSE)


# Import the AM fungal OTU numbers (identified from the phylogeny with reference sequences, Appendix 1, Figure S1).
AMFOTUNumbers <- scan("~/Prairie-AMF-Gradient-Analysis-master/GradientAMF_AMF_OTUNumbers_forR.txt")

inTree <- read.tree("~/Prairie-AMF-Gradient-Analysis-master/GradientAMF_phylogeneticTrees/RAxML_bestTree.GradientSample_AbundOTU97PercOTUs_WithRefSeqs_w_Mor_elo_Outgroup_RAxMLPhylo_v2")

phyloLabels <- inTree$tip.label

labelsToKeep <- phyloLabels[which(substr(phyloLabels,1,4) == "Cons")]

# Drop OTU969
labelsToKeep2 <- labelsToKeep[-which(substr(labelsToKeep,1,12) == "Consensus969")]

# Add Mor elo outgroup
labelsToKeep3 <- c(labelsToKeep2, phyloLabels[length(phyloLabels)])

# The inverse of the labels to keep is the labels to prune
phyloLabels_toPrune <- phyloLabels[-match(labelsToKeep3, phyloLabels)]

# Prune the phylo to only keep the OTU seqs and the outgroup.
prunedPhylo <- drop.tip(inTree, phyloLabels_toPrune)

prunedPhyloLabels <- prunedPhylo$tip.label


# ----
# All results - testing disturbed vs. remnant

DESeq2ResultsAll <- load("~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientCoordinated_DESEQ2_results_allSamples.r")

All_DESeq2_rawResults <- as.data.frame(DESeq_distHistCompare_rawResults@listData)

# The row names of the raw DESeq2 results (OTUs) are in the same order as the OTU numbers in the
# AMFOTUNumbers

All_DESeq2_forNRI <- All_DESeq2_rawResults$log2FoldChange
names(All_DESeq2_forNRI) <- paste0("Consensus",AMFOTUNumbers)

# ----



# ----
# Disturbed results - testing West disturbed vs. East disturbed

DESeq2ResultsDist <- load("~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientCoordinated_DESEQ2_results_disturbedSites.r")

Dist_DESeq2_rawResults <- as.data.frame(DESeq_disturbed_WE_Compare_rawResults@listData)

# The row names of the raw DESeq2 results (OTUs) are in the same order as the OTU numbers in the
# AMFOTUNumbers

Dist_DESeq2_forNRI <- Dist_DESeq2_rawResults$log2FoldChange
names(Dist_DESeq2_forNRI) <- paste0("Consensus",AMFOTUNumbers)

# ----


# ----
# Remnant results - testing West remnant vs. East remnant
DESeq2ResultsRemn <- load("~/Prairie-AMF-Gradient-Analysis-master/autoGeneratedScriptOutput/GradientCoordinated_DESEQ2_results_remnantSites.r")

Remn_DESeq2_rawResults <- as.data.frame(DESeq_remnant_WE_Compare_rawResults@listData)

# The row names of the raw DESeq2 results (OTUs) are in the same order as the OTU numbers in the
# AMFOTUNumbers

Remn_DESeq2_forNRI <- Remn_DESeq2_rawResults$log2FoldChange
names(Remn_DESeq2_forNRI) <- paste0("Consensus",AMFOTUNumbers)

# ----

# Sort by phylogeny labels
All_DESeq2_forNRI_phyloSort <- All_DESeq2_forNRI[match(prunedPhyloLabels, names(All_DESeq2_forNRI))]
Dist_DESeq2_forNRI_phyloSort <- Dist_DESeq2_forNRI[match(prunedPhyloLabels, names(Dist_DESeq2_forNRI))]
Remn_DESeq2_forNRI_phyloSort <- Remn_DESeq2_forNRI[match(prunedPhyloLabels, names(Remn_DESeq2_forNRI))]

# Add the outgroup label (with a zero entry) - this got made with the 'match' above.
All_DESeq2_forNRI_phyloSort[length(All_DESeq2_forNRI_phyloSort)] <- 0
Dist_DESeq2_forNRI_phyloSort[length(Dist_DESeq2_forNRI_phyloSort)] <- 0
Remn_DESeq2_forNRI_phyloSort[length(Remn_DESeq2_forNRI_phyloSort)] <- 0

# Replace the now-matched OTU label names with the pruned label names (that include the outgroup)
names(All_DESeq2_forNRI_phyloSort) <- prunedPhyloLabels
names(Dist_DESeq2_forNRI_phyloSort) <- prunedPhyloLabels
names(Remn_DESeq2_forNRI_phyloSort) <- prunedPhyloLabels

# Keep Deseq2 entries > 0 here (West for Remn or disturbed only; Remnant for all samples)
All_DESeq2_forNRI_phyloSort_REMNANT_ONLY <- ifelse(All_DESeq2_forNRI_phyloSort > 0, 2**All_DESeq2_forNRI_phyloSort, 0)
Dist_DESeq2_forNRI_phyloSort_WEST_ONLY <- ifelse(Dist_DESeq2_forNRI_phyloSort > 0, 2**Dist_DESeq2_forNRI_phyloSort, 0)
Remn_DESeq2_forNRI_phyloSort_WEST_ONLY <- ifelse(Remn_DESeq2_forNRI_phyloSort > 0, Remn_DESeq2_forNRI_phyloSort, 0)

# Keep Deseq2 entries < 0 here (East for Remn or disturbed only; Disturbed for all samples) - take absolute value of them
All_DESeq2_forNRI_phyloSort_DISTURBED_ONLY <- ifelse(All_DESeq2_forNRI_phyloSort < 0, 2**abs(All_DESeq2_forNRI_phyloSort), 0)
Dist_DESeq2_forNRI_phyloSort_EAST_ONLY <- ifelse(Dist_DESeq2_forNRI_phyloSort < 0, 2**abs(Dist_DESeq2_forNRI_phyloSort), 0)
Remn_DESeq2_forNRI_phyloSort_EAST_ONLY <- ifelse(Remn_DESeq2_forNRI_phyloSort < 0, 2**abs(Remn_DESeq2_forNRI_phyloSort), 0)



# Remn_DESeq2_forNRI_phyloSort <- Remn_DESeq2_forNRI[match(prunedPhyloLabels, names(Remn_DESeq2_forNRI))]
# names(Remn_DESeq2_forNRI_phyloSort) <- names(prunedPhyloLabels)

Deseq2_resultsMatrix <- rbind(All_DESeq2_forNRI_phyloSort_DISTURBED_ONLY,
                              All_DESeq2_forNRI_phyloSort_REMNANT_ONLY,
                              Remn_DESeq2_forNRI_phyloSort_WEST_ONLY,
                              Remn_DESeq2_forNRI_phyloSort_EAST_ONLY,
                              Dist_DESeq2_forNRI_phyloSort_WEST_ONLY,
                              Dist_DESeq2_forNRI_phyloSort_EAST_ONLY
                              )

phyloDist <- ape::cophenetic.phylo(prunedPhylo)

# Run the NRI.
set.seed(822)
NRIResult <- ses.mpd(Deseq2_resultsMatrix, phyloDist, null.model="richness", abundance.weighted = TRUE, runs = 1000)
# The richness null model exchanges among entries in each row ('sample'), but not among entries in each column (OTU)
# because the column values really aren't exchangeable across the different DESEQ2 results that I'm using here as
# the rows ('samples').

print(NRIResult)

# Same as -1*mpd.obs.z in NRI results 
NRIValues <- as.matrix(-1*((NRIResult[,2] - NRIResult[,3])/NRIResult[,4]))

# This is for plotting the pruned phylo including genus names for the OTUs on the branch labels

ParsedOTUNames_matchPhylo <- paste0("Consensus", OTUNames_fromPhylo$OTU_num)

# Add the outgroup label
ParsedOTUNames_matchPhylo <- c(ParsedOTUNames_matchPhylo, prunedPhyloLabels[length(prunedPhyloLabels)])

phyloLabelMatch <- match(prunedPhyloLabels, ParsedOTUNames_matchPhylo)

ParsedOTUNames_toReplaceOnPhylo <- paste0("Consensus_", OTUNames_fromPhylo$OTU_num, "_", OTUNames_fromPhylo$Genus_Attribution)
# Add the outgroup label
ParsedOTUNames_toReplaceOnPhylo <- c(ParsedOTUNames_toReplaceOnPhylo, prunedPhyloLabels[length(prunedPhyloLabels)])

prunedPhylo_relabel <- prunedPhylo

prunedPhylo_relabel$tip.label <- ParsedOTUNames_toReplaceOnPhylo[phyloLabelMatch]

# Plot the labelled phylogeny
plot(prunedPhylo_relabel, cex = 0.25)

write.tree(phy = prunedPhylo_relabel, file = "~/Prairie-AMF-Gradient-Analysis-master/GradientAMF_phylogeneticTrees/GradientAMF_prunedOnlyOTU_leaves_withMoreloOutgroup.nwk")
