# LDA using the variable selection with the klar::stepclass function on the 
# rLog transformed OTU tables (need to run that conversion script first) using the same number of
# cross validation folds as used in the random forest analysis. These accuracy results are
# reported in Table 1 for LDA forward and backward model selection.
# 

# This is working correctly. 080717.

# Run the LDA on the rlog-transformed OTU tables; this includes N-fold
# cross validation of the predicted labels, set up like my RF CV.

library(MASS)
library(caret)
# Need this for the confusion matrix function of caret
library(e1071)
library(ggplot2)
library(DESeq2)
library(klaR)

gradientEnvAndSoilChemValues <- read.table("~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/GradientCoordinated_environ_soilNutrient_values_forR.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

subsetGradientEnvAndSoilChemValues_abbrv <- gradientEnvAndSoilChemValues[,-1:-3]
rownames(subsetGradientEnvAndSoilChemValues_abbrv) <- sampleNames

# Import the phylogeny-based genus attributions to each of the OTUs (from Figure S1). These are listed in 
# phylogenetic order e.g. phylogenetically closely related genera are listed immediately before/after one another)
genusAttributions <- read.table("~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/GradientCoordinated_OTU_GenusAttributions_forR.csv", sep = ",", header = TRUE, stringsAsFactors = FALSE)

OTUNamesMatchOTUTable <- paste("X", genusAttributions$OTU_num, sep = "")

# Match is a great function to find the indices of the OTUs in the gradientFrame that match the 
# order of the phylogenetically-sorted OTU names in the OTUNamesMatch. This will be used for sorting the 
# DESeq2 output in phylogenetic order to see if there are consistent differences across the aridity gradient.
OTUTableIndicesInPhylogOrderForLabels <- match(OTUNamesMatchOTUTable, colnames(subsetOTUframeGradient_onlyAMFOTUs))

genusNamesForOTUMatch <- genusAttributions$Genus_Attribution

distGroup <- subsetGradientEnvAndSoilChemValues_abbrv$Disturbed_Remnant

# For the revised analysis 120416
# East/West geographic groups.
# West: Klemme, Stillwater, Hays, Ft. Riley (2013), Konza (2015)
# East: Lawrence (Rockefeller and Welda), SW MO, Morris, IL (2013), IL (2015)
geogrGroupWE <- as.factor(c(rep("W", 7), rep("E", 2), rep("W", 4), rep("E", 8), rep("W", 17), rep("E", 13),
                            rep("W", 4), rep("E", 17), rep("W", 20), rep("E", 3), rep("W", 6), rep("E", 7)))
geogrGroupWE_DF <- as.data.frame(geogrGroupWE)

subsetGradientEnvAndSoilChemValues_abbrv$distGroup <- as.factor(distGroup)

subsetGradientEnvAndSoilChemValues_abbrv$geogrGroupWE <- as.factor(geogrGroupWE)

# ---------------------

runLDA <- function(outputFileName, LDADirection) {
    
    LDA_modelSelect <- klaR::stepclass(x = rlogTransformedOTUTable, grouping = factorForTest, cv.groups = cvFolds, method = "lda", direction = LDADirection,
                                       improvement = 0.01, criterion = "CR")
    
    save(LDA_modelSelect,file = outputFileName)
    
}

#========================
#========================
# ---------------------
# This is for all sites, for testing the Dist/Remn differences.

# Updated 072017
rLogTrans_allSitesPath <- "~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/autoGeneratedScriptOutput/GradientCoordinated_rLogTransformedOTUTable_allSamples.r"
load(rLogTrans_allSitesPath)

# This loads: rlogTransformation_allSites_siteGroupControlled
# Get the OTU table (with samples in the rows) from the loaded data structure
rlogTransformedOTUTable <- as.matrix(t(assay(rlogTransformation_allSites_siteGroupControlled)))

# Creates 10 test folds for LDA accuracy testing that is aware of the disturbance labels while making the folds
# ie the 'disturbed' and 'remnant' samples are roughly evenly distributed among all the folds. This returns a list
# of length 5 with each list element being a vector of indices of the TEST partition (need to use '-' indexing to build
# decision trees on the remaining rows - ie the TRAINING partition). If set the seed immediately before running
# testFolds, it will always return identical folds each time it is run.

numCVFolds <- 10

# This returns a vector the length of the num samples with each entry being the fold assigned to each sample.
set.seed(567)
cvFolds <- createFolds(distGroup, k = numCVFolds, list = FALSE, returnTrain = FALSE)

# This will be passed to the randomForest calc function to select the variable in the input data frame
# to predict on. This makes the randomForest function modular for testing both E/W and dist/remn.
factorForTest <- as.factor(distGroup)

print("****** All samples *******")

# Forward model selection
print("****** Forward *******")
pathToSaveRLogOutput <- "~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/autoGeneratedScriptOutput/"
outputFileName <- "GradientCoordinated_LDA_allSamples_forward.r"
outputFile <- paste(pathToSaveRLogOutput, "/", outputFileName, sep = "")

direction <- "forward"

runLDA(outputFile, direction)

# Backward model selection
print("****** Backward *******")
pathToSaveRLogOutput <- "~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/autoGeneratedScriptOutput/"
outputFileName <- "GradientCoordinated_LDA_allSamples_backward.r"
outputFile <- paste(pathToSaveRLogOutput, "/", outputFileName, sep = "")

direction <- "backward"

runLDA(outputFile, direction)
#--------------------


# ---------------------
# This is for disturbed sites only, for testing the East/West differences.

rLogTrans_distSitesOnlyPath <- "~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/autoGeneratedScriptOutput/GradientCoordinated_rLogTransformedOTUTable_disturbedSites.r"

load(rLogTrans_distSitesOnlyPath)

# This loads: rlogTransformation_DisturbedSites
# Get the OTU table (with samples in the rows) from the loaded data structure
rlogTransformedOTUTable <- as.matrix(t(assay(rlogTransformation_DisturbedSites)))

# Creates 5 test folds for LDA accuracy testing that is aware of the disturbance labels while making the folds
# ie the 'disturbed' and 'remnant' samples are roughly evenly distributed among all the folds. This returns a list
# of length 5 with each list element being a vector of indices of the TEST partition (need to use '-' indexing to build
# decision trees on the remaining rows - ie the TRAINING partition). If set the seed immediately before running
# testFolds, it will always return identical folds each time it is run.

# This will be passed to the randomForest calc function to select the variable in the input data frame
# to predict on. This makes the randomForest function modular for testing both E/W and dist/remn.

geogrGroupWE <- geogrGroupWE[distGroup == 'Disturbed']
factorForTest <- as.factor(geogrGroupWE)


numCVFolds <- 5

set.seed(567)
cvFolds <- createFolds(geogrGroupWE, k = numCVFolds, list = FALSE, returnTrain = FALSE)

print("****** Disturbed sites only *******")

# Forward model selection
print("****** Forward *******")
pathToSaveRLogOutput <- "~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/autoGeneratedScriptOutput/"
outputFileName <- "GradientCoordinated_LDA_disturbedSites_forward.r"
outputFile <- paste(pathToSaveRLogOutput, "/", outputFileName, sep = "")

direction <- "forward"

runLDA(outputFile, direction)

# Backward model selection
print("****** Backward *******")
pathToSaveRLogOutput <- "~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/autoGeneratedScriptOutput/"
outputFileName <- "GradientCoordinated_LDA_disturbedSites_backward.r"
outputFile <- paste(pathToSaveRLogOutput, "/", outputFileName, sep = "")

direction <- "backward"

runLDA(outputFile, direction)


# #--------------------

# ---------------------
# This is for remnant sites only, for testing the East/West differences.

rLogTrans_remnSitesOnlyPath <- "~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/autoGeneratedScriptOutput/GradientCoordinated_rLogTransformedOTUTable_remnantSites.r"

load(rLogTrans_remnSitesOnlyPath)

# This loads: rlogTransformation_RemnantSites
# Get the OTU table (with samples in the rows) from the loaded data structure
rlogTransformedOTUTable <- as.matrix(t(assay(rlogTransformation_RemnantSites)))

# Creates 5 test folds for LDA accuracy testing that is aware of the disturbance labels while making the folds
# ie the 'disturbed' and 'remnant' samples are roughly evenly distributed among all the folds. This returns a list
# of length 5 with each list element being a vector of indices of the TEST partition (need to use '-' indexing to build
# decision trees on the remaining rows - ie the TRAINING partition). If set the seed immediately before running
# testFolds, it will always return identical folds each time it is run.

# This will be passed to the randomForest calc function to select the variable in the input data frame
# to predict on. This makes the randomForest function modular for testing both E/W and dist/remn.


geogrGroupWE <- geogrGroupWE[distGroup == 'Remnant']
factorForTest <- as.factor(geogrGroupWE)

numCVFolds <- 5

# With the revised OTU table 072017 this set.seed() got the LDA stuck with using only 1 OTU
# (no real idea why). Changed the seed and now it works fine.
#set.seed(567)

set.seed(930)
cvFolds <- createFolds(geogrGroupWE, k = numCVFolds, list = FALSE, returnTrain = FALSE)

print("****** Remnant sites only *******")

# Forward model selection
print("****** Forward *******")
pathToSaveRLogOutput <- "~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/autoGeneratedScriptOutput/"
outputFileName <- "GradientCoordinated_LDA_remnantSites_forward.r"
outputFile <- paste(pathToSaveRLogOutput, "/", outputFileName, sep = "")

direction <- "forward"

runLDA(outputFile, direction)

# Backward model selection
print("****** Backward *******")
pathToSaveRLogOutput <- "~/Box Sync/R_code/Gradient_SequenceAndEnviron_Analysis/ScriptsForGitHubArchiving/autoGeneratedScriptOutput/"
outputFileName <- "GradientCoordinated_LDA_remnantSites_backward.r"
outputFile <- paste(pathToSaveRLogOutput, "/", outputFileName, sep = "")

direction <- "backward"

runLDA(outputFile, direction)

# #--------------------